name: docker build

on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      actions:
        description: "build/depoly"
        default: "build"

jobs:
  build:
    if: ${{ github.event.inputs.actions == 'build' || github.event.inputs.actions == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Build yacreader
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --file ./yacreaderlibraryserver/Dockerfile ./yacreaderlibraryserver
